site_name: bLazing fast Lua for Unity
site_url: https://www.blua-lang.org
site_author: bLua Team
site_description: bLazing fast Lua for Unity!

repo_name: blua-devs/blua
repo_url: https://github.com/blua-devs/blua

theme:
  name: material
  logo: assets/logo-nobackground.png
  favicon: assets/logo.png
  font:
    text: Sora
    code: DM Mono
  features:
    - content.code.annotate
    - content.tooltips
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - header.autohide
    - content.tabs.link
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

extra_css:
  - stylesheets/extra.css

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/blua-devs
      name: The bLua Team on GitHub
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/RZs4T3w3rR
      name: bLua Discord community
    
copyright: bLua, bLazing fast Lua for Unity!

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      
nav:
  - Home: index.md
  - Getting started:
    - Installation: installation.md
    - Running Lua: running-lua.md
    - User Data: user-data.md
  - Downloads: downloads.md